### ISSUE TITLE
TypeError trying to get ING transactions

### ISSUE THREAD

**Issue by ivanperez-keera** [bank-scrap/bank_scrap#27]
Hi

When I run the script to get my ING transactions, I get the error below:
```
/home/dash/.rvm/rubies/ruby-2.1.4/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `initialize': -2.0000000012158385 is not a symbol (TypeError)
	from /home/dash/.rvm/rubies/ruby-2.1.4/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `initialize'
	from /home/dash/.rvm/rubies/ruby-2.1.4/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/dash/.rvm/rubies/ruby-2.1.4/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/dash/.root/opt/gems/gems/rmagick-2.15.2/lib/rmagick_internal.rb:12:in `<top (required)>'
	from /home/dash/.rvm/rubies/ruby-2.1.4/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/dash/.rvm/rubies/ruby-2.1.4/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/dash/.root/opt/gems/gems/rmagick-2.15.2/lib/rmagick.rb:1:in `<top (required)>'
	from /home/dash/.rvm/rubies/ruby-2.1.4/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:128:in `require'
	from /home/dash/.rvm/rubies/ruby-2.1.4/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
	from /home/dash/.rvm/rubies/ruby-2.1.4/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	from /home/dash/.root/opt/bank_scrap/lib/bank_scrap/banks/ing.rb:3:in `<top (required)>'
	from /home/dash/.root/opt/bank_scrap/lib/bank_scrap/cli.rb:80:in `const_get'
	from /home/dash/.root/opt/bank_scrap/lib/bank_scrap/cli.rb:80:in `find_bank_class_for'
	from /home/dash/.root/opt/bank_scrap/lib/bank_scrap/cli.rb:75:in `initialize_client_for'
	from /home/dash/.root/opt/bank_scrap/lib/bank_scrap/cli.rb:22:in `balance'
	from /home/dash/.root/opt/gems/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /home/dash/.root/opt/gems/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/dash/.root/opt/gems/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /home/dash/.root/opt/gems/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from ./bank_scrap/bin/bank_scrap:5:in `<main>
```

Any ideas?

**Comment by javiercr** [comment]
@raulmarcosl can you take a look to this? it looks like is an error from rmagick, so probably is the virtual keyboard processing.

**Comment by raulmarcosl** [comment]
I've updated the ING integration, and I've pushed a new gem version, but I didn't change anything related to rmagick. Could you try the 0.0.16 version to see if that solves your problem?

**Comment by ivanperez-keera** [comment]
Works. Thanks! :)
